# -*- coding: utf-8 -*-
"""MyeuMerDelivery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLkqSgDMJoqt_Xi9YGS1rWuThm4PbDzn
"""

import streamlit as st
import pandas as pd
import gspread
import requests
import base64
import io
from PIL import Image
from google.oauth2.service_account import Credentials
from datetime import datetime, timedelta

# --- CẤU HÌNH BẢO MẬT & SESSION ---
if "authenticated" not in st.session_state:
    st.session_state.authenticated = False
if "picker_id" not in st.session_state:
    st.session_state.picker_id = ""

VALID_PASSWORDS = {"0519": "Lê Phương", "PICKER-AN": "An"}

if not st.session_state.authenticated:
    st.markdown("### 🔒 Cổng kiểm soát nội bộ (Trạm Giao Hàng)")
    password = st.text_input("Nhập mã truy cập cá nhân:", type="password")

    if st.button("Đăng nhập"):
        if password in VALID_PASSWORDS:
            st.session_state.authenticated = True
            st.session_state.picker_id = VALID_PASSWORDS[password]
            st.rerun()
        else:
            st.error("Mã không hợp lệ hoặc đã bị vô hiệu hóa!")
    st.stop()

# --- CẤU HÌNH GIAO DIỆN CHUẨN TONE ---
st.set_page_config(page_title="MYÊU PICKER", layout="centered")

st.markdown("""
<style>
    .main-title {
        color: #C71585;
        text-shadow: 2px 2px 0px #e6d3d3, 4px 4px 5px rgba(0,0,0,0.4);
        text-align: left;
        font-weight: 900;
        font-size: 2.5rem;
        line-height: 1.2;
        margin-bottom: 25px;
    }
    .main-title span { display: block; white-space: nowrap; }
    .highlight-text { color: #C71585; font-weight: bold; font-size: 1.1rem; }
    div.stButton > button {
        background: linear-gradient(90deg, #C71585, #8B008B) !important;
        color: white !important;
        border: none !important;
        font-weight: bold !important;
        border-radius: 8px !important;
        transition: 0.3s;
    }
    div.stButton > button:hover {
        background: linear-gradient(90deg, #8B008B, #C71585) !important;
        box-shadow: 0px 4px 10px rgba(139, 0, 139, 0.4) !important;
    }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-title"><span>MYÊU MERCHANDISE</span><span>DELIVERY</span></div>', unsafe_allow_html=True)
st.caption(f"🏃 Đang trực trạm giao hàng: **{st.session_state.picker_id}**")
st.markdown("---")

# --- KẾT NỐI API & UPLOAD ---
OUTPUT_SHEET_URL = "https://docs.google.com/spreadsheets/d/1zSeYfiaSFJNdXMOZnwG7WsW0b33v-rbt0EruvMS_aA0/edit"
# DÁN LINK APPS SCRIPT VÀO ĐÂY NHA:
LINK_WEB_APP = "https://script.google.com/macros/s/AKfycbwK7XqRKonpA1FqU1fhoXh4BWbQCHyInVibnutuM0aZzWkaozezKXojDF4xDSCaNlQ43g/exec"

@st.cache_resource
def get_gspread_client():
    scopes = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
    creds = Credentials.from_service_account_info(st.secrets["gcp_service_account"], scopes=scopes)
    return gspread.authorize(creds)

client = get_gspread_client()

def upload_image_to_gdrive_script(photo_file, filename):
    try:
        img = Image.open(photo_file)
        if img.mode in ("RGBA", "P"): img = img.convert("RGB")
        img.thumbnail((1024, 1024))
        compressed_io = io.BytesIO()
        img.save(compressed_io, format='JPEG', quality=70)
        compressed_bytes = compressed_io.getvalue()

        encoded_image = base64.b64encode(compressed_bytes).decode('utf-8')
        payload = {"fileData": encoded_image, "contentType": "image/jpeg", "filename": filename}
        response = requests.post(LINK_WEB_APP, data=payload)
        return response.text if response.text.startswith("http") else None
    except Exception as e:
        st.error(f"Lỗi nén/up ảnh: {e}")
        return None

# --- LOGIC GET ĐƠN & GIAO HÀNG ---
# Khởi tạo bộ đếm trong session
if "delivery_stats" not in st.session_state:
    st.session_state.delivery_stats = {}

if st.button("Thông tin MYêu nhận Mer", use_container_width=True):
    try:
        sheet = client.open_by_url(OUTPUT_SHEET_URL).sheet1
        all_records = sheet.get_all_records()
        df = pd.DataFrame(all_records)

        # 1. Lọc ra các dòng chưa Completed
        df_pending = df[df['Status'].astype(str).str.strip() != 'Completed']

        if df_pending.empty:
            st.success("Tạm thời không có đơn hàng nào chờ giao!")
        else:
            # 2. Sort theo Thời gian, lấy cái cũ nhất
            df_pending['Thời Gian'] = pd.to_datetime(df_pending['Thời Gian'])
            df_pending = df_pending.sort_values(by='Thời Gian')

            # 3. Lấy ĐT hoặc Mã Đơn của người đầu tiên để gom nhóm
            first_row = df_pending.iloc[0]
            target_phone = first_row['ĐT']
            target_order = first_row['Mã đơn hàng']
            target_name = first_row['Tên']

            # Gom tất cả hàng của người này
            user_items = df_pending[(df_pending['ĐT'] == target_phone) & (df_pending['Mã đơn hàng'] == target_order)]

            # Lấy index để cập nhật sau này (cộng 2 vì header ở dòng 1 và zero-index)
            row_indices = user_items.index.tolist()

            st.session_state.current_user = {
                "name": target_name,
                "order_code": str(target_order),
                "items": user_items.to_dict('records'),
                "row_indices": row_indices
            }

    except Exception as e:
        st.error(f"Lỗi khi tải dữ liệu: {e}")

# Nếu đang có đơn hàng chờ xử lý trong session
if "current_user" in st.session_state:
    user_data = st.session_state.current_user

    st.markdown(f"### Khách hàng: <span class='highlight-text'>{user_data['name']}</span>", unsafe_allow_html=True)

    for i, item in enumerate(user_data['items']):
        size_txt = f" - Size {item['Size áo']}" if item['Size áo'] else ""
        st.markdown(f"{i+1}. {item['Loại Merchandise']}{size_txt} - {item['SL']} cái")

    st.markdown("---")
    photo = st.file_uploader("Chụp hóa đơn/bằng chứng", type=['png', 'jpg', 'jpeg'])

    if st.button("Hoàn Thành Giao Hàng", type="primary"):
        if photo is None:
            st.warning("Bạn quên chụp hình bằng chứng rồi!")
        else:
            with st.spinner("Đang lưu hình và chốt đơn..."):
                # Đặt tên hình = 3 số đuôi mã đơn
                suffix = user_data['order_code'][-3:] if len(user_data['order_code']) >= 3 else user_data['order_code']
                file_name = f"Merch_{suffix}.jpg"

                img_url = upload_image_to_gdrive_script(photo, file_name)

                if img_url:
                    sheet = client.open_by_url(OUTPUT_SHEET_URL).sheet1
                    # Cập nhật Status và Link hình cho TẤT CẢ dòng của khách này
                    for idx in user_data['row_indices']:
                        sheet_row = idx + 2
                        sheet.update_cell(sheet_row, 9, "Completed") # Cột 9 là Status
                        sheet.update_cell(sheet_row, 10, img_url)    # Cột 10 là Link hình

                        # Cập nhật Thống kê Realtime trên App 2
                        item_name = user_data['items'][idx - user_data['row_indices'][0]]['Loại Merchandise']
                        st.session_state.delivery_stats[item_name] = st.session_state.delivery_stats.get(item_name, 0) + 1

                    st.success("✅ Đã hoàn tất giao hàng và ghi nhận lên hệ thống!")
                    del st.session_state.current_user
                    st.rerun()
                else:
                    st.error("Up hình thất bại, vui lòng thử lại!")

# --- THỐNG KÊ ĐÃ GIAO TRÊN TRẠM 2 ---
if st.session_state.delivery_stats:
    st.markdown("---")
    st.markdown("### 📊 Thống kê đã xuất kho ca này:")
    for item, count in st.session_state.delivery_stats.items():
        st.markdown(f"- **{item}**: {count} cái")